### PR TITLE
BREAKING: Reconfigure haproxy logging. Drop most distributions.

### LINKED ISSUE #6: Enable molecule tests
See initial attempt in https://github.com/openmicroscopy/ansible-role-haproxy/pull/1

@manics says:

> Our use of the role has diverged significantly from the upstream which appears to be aimed at web proxying with multi-OS support. I think we should strip out all the tests and create a molecule test from scratch following a similar pattern to our other roles.

### PR DESCRIPTION
**Pull request by manics**
- Bug fix: Attempt to restart rsyslog/haproxy so that logs appear immediately after installation.
- New feature: Separates log files for backend status, http frontends, tcp frontends (disabled by default as it involves rsyslog configuration)
- Breaking: Replace test with molecule, only support CentOS 7 and Ubuntu 16.04

Tag: `3.0.0`

Closes https://github.com/openmicroscopy/ansible-role-haproxy/issues/6

### CODE REVIEW

**Comment by joshmoore** [comment]
Generally, :+1: for only our supported platforms and the molecule configuration.

Do you have a commit somewhere which shows the required downstream changes?

**Comment by manics** [comment]
The only playbook I'm aware of that uses this is in IDR/deployment. The only change required would be the addition of `haproxy_syslog_enable: True`

**Comment by joshmoore** [comment]
Ah, perhaps I misunderstood "disabled by default as it involves rsyslog configuration". In this case, you mean that rsyslog is enabled in idr/deployment and therefore this is fulfilled?

**Comment by manics** [comment]
Previously logging was enabled by setting the syslog facility: https://github.com/IDR/deployment/blob/IDR-0.4.6/ansible/idr-haproxy.yml#L48

Since I've added more (optional) logfiles it made sense to have a single top-level var to control logging and adding defaults for the three separate facilities.

**Comment by joshmoore** [comment]
Ok, so here's a summary of what I understand:

 * 2.x behavior was disabled by default; same for 3.x
 * 2.x enabling required setting log; 3.x requires setting boolean
 * there's no change to the requirement for (r)syslog

The only question I have left is: am I overlooking the usage of `haproxy_syslog_dest_tcp`? It doesn't look like it's ever used to activate anything.

**Comment by manics** [comment]
I've kept the existing test haproxy config, so `haproxy_syslog_dest_tcp` isn't used. It will be used in the IDR which has a custom template where opaque TCP streams are currently being proxied, but we'll want to proxy HTTP too in the future.

**Comment by joshmoore** [comment]
That seems to violate https://en.wikipedia.org/wiki/Principle_of_least_astonishment -- other than it requires another commit and we aren't testing it, is there a reason to not go ahead and add the stanza to the template so someone knows how to consume this new variable?

**Comment by manics** [comment]
Updated

**Comment by joshmoore** [comment]
Wow. Thank you. Changes look good. Merging & releasing.

**Comment by joshmoore** [comment]
`3.0.0` pushed.

**Pull request merged**
