### PR TITLE
Enable molecule tests

### PR DESCRIPTION
**Pull request by joshmoore**
See openmicroscopy/ome-ansible-molecule-dependencies#3

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [ANSIBLE-merge#2](https://ci.openmicroscopy.org/job/ANSIBLE-merge/2/). See the [console output](https://ci.openmicroscopy.org/job/ANSIBLE-merge/2/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - .travis.yml

**Comment by joshmoore** [comment]
Updated to prefer molecule over https://gist.github.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/

**Comment by joshmoore** [comment]
`fatal: [ansible-role-haproxy]: FAILED! => {"changed": false, "failed": true, "msg": "no service or tool found for: haproxy"}
`

**Comment by manics** [comment]
Try using the systemd docker image?

**Comment by manics** [comment]
Our use of the role has diverged significantly from the upstream which appears to be aimed at web proxying with multi-OS support. I think we should strip out all the tests and create a molecule test from scratch following a similar pattern to our other roles.

**Comment by joshmoore** [comment]
So just close this? Or disable everything here?

**Comment by manics** [comment]
Ideally me/you/someone else should takeover this branch and get it working? Maybe test just two distributions, Centos 7 and Ubuntu 16.04?

**Comment by sbesson** [comment]
NB: just enabled issues on this fork. If there is no capacity to tackle this, should we consider capturing this as one issues and close this?

**Comment by joshmoore** [comment]
see https://github.com/openmicroscopy/ansible-role-haproxy/issues/6

**Pull request closed without merging**
