### PR TITLE
add support for bind params

### PR DESCRIPTION
**Pull request by bverschueren**
- support bind params to be set for front-ends
- include test case where bind_params is used to setup ssl termination

### CODE REVIEW

**Comment by joshmoore** [comment]
Hi thanks for this. Can you base your work on https://github.com/openmicroscopy/ansible-role-haproxy/pull/12 please since that has been reviewed and is slated for release?

**Comment by bverschueren** [comment]
Ok, rebased on top of #12.

**Comment by sbesson** [comment]
Thanks @bverschueren, deployed these changes on our production instances and we can confirm the default behavior is currently unmodified. Reviewed internally and the addition of support for extra bind parameters makes sense. Integrating in a `3.2.0` release

**Comment by sbesson** [comment]
This is now integrated in the 3.2.0 release of `openmicroscopy.haproxy` available from https://galaxy.ansible.com/openmicroscopy/haproxy/

**Pull request merged**
