### PR TITLE
Add more customization options

### PR DESCRIPTION
**Pull request by ajardan**
- Add posibility to specify backend params (not only options)
- Add posibility to specify extra backend options

### CODE REVIEW

**Comment by manics** [comment]
Hi @ajardan, thanks for your PR. We've got another PR open here which looks quite similar: https://github.com/openmicroscopy/ansible-role-haproxy/pull/11

Would you mind taking a look, and let us know if it fulfils your requirements?

**Comment by ajardan** [comment]
@manics Looks quite similar, yes, but there are some cons:
- Having opts and options in the backend config will be error prone, since it is not very clear which one is used for what section (unless you look into the template)
- vars also doesn't sound proper to me. These are params or options for the back/front-end
- Documentation was not updated to reflect the new functionality

I could add the multiple bind functionality, or maybe the 2 pull requests can be combined in one commit by a maintainer to get the best for the 2 requests :)

**Comment by ajardan** [comment]
Pushed the updates discussed in #11

**Comment by joshmoore** [comment]
Thanks for the work on this, @ajardan. I think molecule suggests that your `backend.extra_opts` will also need a ` | default([])`:

```
TASK [ansible-role-haproxy : Copy HAProxy configuration in place.] *************
fatal: [haproxy-c7]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'extra_opts'"}
fatal: [haproxy-u1604]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'extra_opts'"}
```

**Comment by ajardan** [comment]
Sorry for the long fix, was a bit busy lately as well. Please let me know if now it's ok.

**Comment by joshmoore** [comment]
Travis looks happy and this looks generally straight-forward. We still don't have a concrete use-case on our side, so opinions from others welcome. If none, then I'd propose that we add this as `3.1.0`

**Comment by ajardan** [comment]
My specific use-case was to set a specific check port on backend servers, since backend servers in my setup run a health service on a different port. Would also help setting up stickiness, etc

**Comment by sbesson** [comment]
Thanks @ajardan and apologies for the delay here. Thanks for your suggested changes and for combining the updates from #11 in here.
We are going to test these changes in one of our large-scale testing deployments using this role (see https://github.com/IDR/deployment/pull/122) and get back to you. Assuming everything works as expected, we'll try to cut a `3.1.0` release of this role asap.

**Comment by ajardan** [comment]
No worries, good luck with the tests ! Let me know if anything should be adjusted.

**Comment by sbesson** [comment]
Thanks again @ajardan this has now been released as 3.1.0 -see  https://galaxy.ansible.com/openmicroscopy/haproxy/

**Comment by ajardan** [comment]
Thank you !

**Pull request merged**
