### PR TITLE
make package name configurable

### PR DESCRIPTION
**Pull request by bverschueren**
When installing newer versions of haproxy (e.g. from SCL repo's) the package name is different and thus making this configurable can be useful.

### CODE REVIEW

**Comment by manics** [comment]
Thanks for your PR. What's the name of the package in the SCL repo you're using? I'm wondering if the variable could instead be the source repo (e.g. `dist`, `scl`, etc)?

**Comment by bverschueren** [comment]
This depends on the purpose (our repos are configured based on the hosts purpose). In case a PAAS repo is used the package name is "haproxy18", but in other cases it might be "rh-haproxy18". 

Specifying the repo might be a good addition if the repo is not configured by some external tool, but I'm afraid that won't be sufficient to fetch the right package.

**Comment by sbesson** [comment]
@bverschueren with #12 merged, this now conflicts, could you merge `origin/master` into this branch?

**Comment by sbesson** [comment]
Overall looks generally good as an extension point allowing to override the default package name in specific use cases. As you are extending the default dictionary, do you also want to document this addition in the top-level README or is it sufficient to keep it internal for now?

**Review by sbesson — APPROVED** [review]

**Comment by sbesson** [comment]
This is now integrated in the 3.2.0 release of `openmicroscopy.haproxy` available from https://galaxy.ansible.com/openmicroscopy/haproxy/

**Pull request merged**
