### PR TITLE
Improve haproxy.cfg indentation, replace extra_addresses with address supporting strings as well as lists

### PR DESCRIPTION
**Pull request by killua-eu**
The way we use this role forces us to use  extra_addresses extensively. To prevent too large configs, I've removed ``{{ extra_addresses }}`` completely in favour for supporting ``{{ address }}`` assuming both types, strings and lists. As a result, both notations are possible:

```
- ...
  address: '10.1.1.1:80'
- ...
  address: 
    - '10.1.1.2:443'
    - '10.1.1.3:443'
```

### CODE REVIEW

**Comment by sbesson** [comment]
Thanks for your contribution @killua-eu. Adding support both for string and list types certainly sounds like an interesting approach to extend the `address` parameter although I do not know whether there is some downside to this flexibility.

As this effectively reverts the `extra_addresses` variable discussed in https://github.com/openmicroscopy/ansible-role-haproxy/pull/11#issuecomment-380825388 and implemented in #12 , it would be good to hear @ajardan and @joshmoore's thoughts on whether this new proposal would cover all their use cases. If so, we can then agree on whether a straight breaking change is preferable or whether deprecating `extra_addresses` would be preferable first.

**Comment by ajardan** [comment]
This definitely looks much more elegant, so I would vote for removing extra_addresses

**Comment by joshmoore** [comment]
@killua-eu : did you intend to update this PR?

**Comment by killua-eu** [comment]
@joshmoore, nope sorry, my mistake. Will revert once back at my pc

**Comment by joshmoore** [comment]
@killua-eu : note, this is now closed rather than reverted.

**Pull request closed without merging**
